# Generated by Django 4.2.11 on 2024-05-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba_td', '0005_order_product_user_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
